name: Deploy Docker

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: takashiidobe 
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true 
          tags: |
            ghcr.io/takashiidobe/test-ghcr:v0.0.1
            ghcr.io/takashiidobe/test-ghcr:latest
